#!/bin/bash
# Runs once, on first start of an empty volume.
set -euo pipefail
psql -v ON_ERROR_STOP=1 -U postgres <<SQL
CREATE ROLE sog LOGIN PASSWORD '${SOG_DB_PASSWORD}';
CREATE DATABASE sog OWNER sog;
CREATE ROLE n8n LOGIN PASSWORD '${N8N_DB_PASSWORD}';
CREATE DATABASE n8n OWNER n8n;
REVOKE CONNECT ON DATABASE sog FROM PUBLIC;
REVOKE CONNECT ON DATABASE n8n FROM PUBLIC;
GRANT CONNECT ON DATABASE sog TO sog;
GRANT CONNECT ON DATABASE n8n TO n8n;
SQL
psql -v ON_ERROR_STOP=1 -U postgres -d sog -c "CREATE EXTENSION IF NOT EXISTS vector; CREATE EXTENSION IF NOT EXISTS pg_trgm;"
